os: Visual Studio 2015
configuration: Release
platform: Any CPU

environment:
  ANDROID_HOME: C:\android-sdk
  AndroidSdkDirectory: C:\android-sdk
   
# xamarin:
#   email: EMAIL@ADDRESS.HE.RE
#   password:
#     secure: SECURE_PASSWORD_HERE
#   android: true
#   ios: true

build_script:
 - cmd: mklink /j %ANDROID_HOME% "C:\Program Files (x86)\Android\android-sdk"
 - cmd: echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter platform-tools,tools,android-23,android-19
 - cmd: .\MakefileAll.bat
  
before_build:
- ps: >-
    $nuspec1 = "source\Xamarin.FFImageLoading.nuspec"
    $nuspec2 = "source\Xamarin.FFImageLoading.Forms.nuspec"
    $nuspec3 = "source\Xamarin.FFImageLoading.Transformations.nuspec"  

    $version = env:appveyor_build_version
    $branch = $env:appveyor_repo_branch 
    
    If (-Not $env:appveyor_repo_tag) {
        $version = ("{0}-pre" -f $version)
    }
    
    If ($branch -ine "master") {
        $version = ("{0}-{1}" -f $version, $branch)
    }
          
    cat ($nuspec1 + ".template") | % { $_ -replace "@version", $version } > $nuspec1
    cat ($nuspec2 + ".template") | % { $_ -replace "@version", $version } > $nuspec2
    cat ($nuspec3 + ".template") | % { $_ -replace "@version", $version } > $nuspec3        
  
artifacts:
 - path: Xamarin.FFImageLoading.*.nupkg
